name: EC2 Print Demo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull repo and show scybers.txt from EC2
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          # Save private key
          echo "$EC2_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # Pull latest repo and show file
          ssh -o StrictHostKeyChecking=no -i key.pem $SERVER_USER@$SERVER_IP "
            cd /home/$SERVER_USER/repo || exit
            git pull
            cat scybers.txt
          "


